### ISSUE TITLE
README: clearSession example 

### ISSUE THREAD

**Issue by kfuquay** [matteocargnelutti/netlify-functions-session-cookie#3]
The argument passed to `clearSession()` should be the `context` object rather than `session` in the code example for `clearSession()`.  

`session` in the example is a reference to `context.clientContext.sessionCookieData` (the return value of `getSession()`).

---

The code-snippet found in README:
`clearSession(session); // Will clear the session object in place.`

Suggested edit:
`clearSession(context); // Will clear the session object in place`

**Comment by matteocargnelutti** [comment]
Good find 🔍 ! Thank you very much @kfuquay !

I [pushed a fix](https://github.com/matteocargnelutti/netlify-functions-session-cookie/commit/e4060a3fa3c03d420c1e1fb8e85f01a89c99acf6) for this 😄 .
